### ISSUE TITLE
how to unzip and decrypt

### ISSUE THREAD

**Issue by JohnHwangx** [ksoichiro/node-archiver-zip-encryptable#4]
It is seem easy to zip and encrypt files, but how could I unzip and decrypt them?

**Comment by ksoichiro** [comment]
Unzip(decrypt) is not supported yet.
If you need it, I'll consider developing it.

**Comment by dipeshsingh2012** [comment]
Please provide the functionality of decrypting also. Thanks

**Comment by ksoichiro** [comment]
As you already know, this package depends on node-archiver, but it seems node-archiver does not support unzipping currently.
So if you need this functionality, maybe we need to create a new project based on some package like [yauzl](https://www.npmjs.com/package/yauzl) and [extract-zip](https://www.npmjs.com/package/extract-zip).
Any suggestions for this?

**Comment by ksoichiro** [comment]
If you have any suggestions, please reopen this issue.
