### ISSUE TITLE
<Buffer > / empty file causes error when unzipping

### ISSUE THREAD

**Issue by simple-nguyen** [ksoichiro/node-archiver-zip-encryptable#6]
Hey, 

Thanks for the awesome library. I have noticed that if I pass in an empty file (eg. blank.txt) and I observe the Buffer for this file (ie. <Buffer >), when I try to unzip the file produced by the archiver, it does not allow me to unzip.

I tried ensuring that it was not node-archiver which is the issue (ie. not registering archiver-zip-encryptable as the format) and I can unzip and see that the blank.txt is indeed empty.

Can you shed any light on this?

**Comment by ksoichiro** [comment]
Thank you for your report.
I confirmed it.
I'll fix this later.

**Comment by ksoichiro** [comment]
I've fixed it (#7) and released as v1.0.4.

**Comment by simple-nguyen** [comment]
Yea awesome work again. Do you have a source reference so I can better understand how zipping works at a lower level.

I've also noticed that if I tried to set stored: true and append buffers then I also have the same problem with unzipping and was trying to work out how to get that to work too. (unfortunately I could work my head around how this all works just yet)

**Comment by simple-nguyen** [comment]
Yea awesome work again. Do you have a source reference so I can better understand how zipping works at a lower level.

I've also noticed that if I tried to set stored: true and append buffers then I also have the same problem with unzipping and was trying to work out how to get that to work too. (unfortunately I could work my head around how this all works just yet)
